#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate the master authority page
(/about/straight-flush-plumbing-orange-county/) into the site repo as a PR.

The page makes the business entity explicit and verifiable: canonical NAP,
Organization + LocalBusiness(Plumber) + WebSite + BreadcrumbList schema,
verified sameAs, service + service-area + internal-link architecture.
Nothing fabricated — unverified facts are [VERIFY] placeholders.

Usage:
  python3 scripts/gen_authority_page.py --site-repo OWNER/REPO
  python3 scripts/gen_authority_page.py --no-open-pr       # local only
"""
import argparse
import os
import shutil
import subprocess
import sys
import tempfile

_SCRIPTS = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.dirname(_SCRIPTS)
for p in (_SCRIPTS, _REPO):
    if p not in sys.path:
        sys.path.insert(0, p)

from modules.objects import authority_page as A  # noqa: E402
from modules.objects import site_data as S  # noqa: E402
from modules.objects import sitemap as SITEMAP  # noqa: E402

DEFAULT_SITE_REPO = os.environ.get("SFGE_SITE_REPO", "straightflushplumbing03/-Up2datewebsiteseo")


def run(cmd, cwd=None):
    proc = subprocess.run(cmd, cwd=cwd, text=True, capture_output=True)
    if proc.returncode != 0:
        raise RuntimeError(f"cmd failed: {cmd}\n{proc.stdout}\n{proc.stderr}")
    return proc.stdout.strip()


def gh_request(method, api_path, body=None, token=None):
    import json
    import urllib.error
    import urllib.request
    req = urllib.request.Request(
        f"https://api.github.com/{api_path.lstrip('/')}", method=method)
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Accept", "application/vnd.github+json")
    data = json.dumps(body).encode() if body is not None else None
    if data:
        req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, data=data, timeout=60) as r:
            raw = r.read().decode()
            return r.status, (json.loads(raw) if raw else {})
    except urllib.error.HTTPError as e:
        raw = e.read().decode("utf-8", "replace")[:500]
        return e.code, {"error": raw}


def main():
    ap = argparse.ArgumentParser(description="Generate master authority page PR")
    ap.add_argument("--site-repo", default=DEFAULT_SITE_REPO)
    ap.add_argument("--no-open-pr", action="store_true",
                    help="write the page locally without pushing/opening a PR")
    args = ap.parse_args()

    token = os.environ.get("GITHUB_TOKEN", "")
    if not args.no_open_pr and not token:
        sys.exit("[sfge] GITHUB_TOKEN not set; refusing to open a PR")

    result = A.build_authority_page()
    branch = f"sfge/authority-page"
    worktree = tempfile.mkdtemp(prefix="sfge-auth-")
    try:
        clone_url = os.environ.get("SFGE_SITE_CLONE_URL",
                                   f"https://github.com/{args.site_repo}.git")
        run(["git", "clone", "--depth", "1", "--branch", "main", clone_url, worktree])
        run(["git", "config", "user.email", "sfge-engine@users.noreply.github.com"], worktree)
        run(["git", "config", "user.name", "SFGE Engine"], worktree)

        out = os.path.join(worktree, A.FILENAME)
        os.makedirs(os.path.dirname(out), exist_ok=True)
        with open(out, "w", encoding="utf-8") as f:
            f.write(result["html"])
        print(f"[sfge] wrote {out}")

        sitemap_path = os.path.join(worktree, "sitemap.xml")
        if os.path.exists(sitemap_path):
            SITEMAP.patch_sitemap(sitemap_path, result["canonical_path"], priority="0.9")
            print(f"[sfge] patched sitemap.xml with {result['canonical_path']}")

        run(["git", "checkout", "-b", branch], worktree)
        run(["git", "add", "-A"], worktree)
        added = run(["git", "diff", "--cached", "--name-only", "--diff-filter=A"],
                    worktree).splitlines()
        if added:
            run(["git", "commit", "-m",
                 f"Add master authority page: {result['title']}\n\nGenerated by SFGE. "
                 "Human review required before merge."], worktree)
            print(f"[sfge] committed {len(added)} files on branch {branch}")

        if args.no_open_pr:
            print(f"[sfge] --no-open-pr: branch {branch} ready at {worktree}")
            return

        push_url = os.environ.get(
            "SFGE_PUSH_URL",
            f"https://x-access-token:{token}@github.com/{args.site_repo}.git",
        )
        run(["git", "push", "-u", push_url, branch], worktree)
        status, pr = gh_request(
            "POST", f"repos/{args.site_repo}/pulls",
            body={
                "title": f"Add master authority page: {result['title']}"[:200],
                "head": branch,
                "base": "main",
                "body": (
                    "Automated authority page generated by **SFGE**. "
                    "Makes the business entity explicit and verifiable:\n\n"
                    "- Canonical NAP, hours, founding year (from the site's own verified data)\n"
                    "- Organization + LocalBusiness(Plumber) + WebSite + BreadcrumbList schema\n"
                    "- Verified sameAs (Yelp, Google Business Profile share link); others tracked as TODO\n"
                    "- Humans-first company page: who/what/where/services/diagnostic approach\n"
                    "- Internal links to services, city pages, academy, case studies\n"
                    "- Added to sitemap.xml\n\n"
                    "**Guardrail:** requires human review before merge — never auto-merged.\n\n"
                    "_This PR was created by an AI agent (OpenHands) on behalf of the Straight Flush team._"
                ),
            },
            token=token,
        )
        if status != 201:
            print(f"[sfge] PR open FAILED ({status}): {pr.get('error', pr)}")
            sys.exit(1)
        print(f"[sfge] PR: {pr.get('html_url')}")
    finally:
        shutil.rmtree(worktree, ignore_errors=True)


if __name__ == "__main__":
    main()